#!/bin/sh
# control screen brightness
# USAGE: brightness (up|down)
# file in $DIR/brightness must be writeable by user

DIR=/sys/class/backlight/acpi_video0

MIN_LEVEL=0
MAX_LEVEL=`cat $DIR/max_brightness`
CUR_LEVEL=`cat $DIR/brightness`

UP="up"
DOWN="down"

function increase {
	if [ $CUR_LEVEL -ge $MAX_LEVEL ]; then
		quit
	else
		let NEW_LEVEL=$CUR_LEVEL+1
		change $NEW_LEVEL
	fi;
}

function decrease {
	if [ $CUR_LEVEL -le $MIN_LEVEL ]; then
		quit
	else
		let NEW_LEVEL=$CUR_LEVEL-1
		change $NEW_LEVEL
	fi;
}

function change {
	`echo $1 | dd of=$DIR/brightness`
}

function quit {
	exit 0
}

if [ $1 = $UP ]; then
	increase
elif [ $1 = $DOWN ]; then
	decrease
fi;

