#!/bin/bash
set -e

java_file="$1"

if [[ $# != 1 ]] || [[ "$1" == "--help" ]] || [ ! -f "$java_file" ]; then
    echo "Usage: $(basename $0) <path/to/Main.java>"
    echo "       Compiles and runs a Java file."
    echo "       The Java file needs to have a class with the same name in the default package (root)."
    exit 1
fi

file_without_ext=${java_file%.*}
class_file="${file_without_ext}.class"
directory=$(dirname $java_file)
class_name=${file_without_ext##*/}

javac "$java_file"
java -cp "$directory" "$class_name" || echo -n ""
rm "$class_file"
