#!/bin/bash
# pacnew-update - merge *.pacnew files with original configurations with meld

pacnew=$(find /etc -type f -name "*.pacnew")

for config in $pacnew; do
  sudo meld ${config%\.*} $config &
  echo "you have to manually delete $config"
  wait
done
