#!/bin/bash
for i in `find . -type d -print -name ".svn" | grep -v "/\.svn"`
do
    if [ -z "`ls -A $i | grep -v '\.svn' `" ]
    then
		if [ "$1" == "-r" ]; then
			echo Removing $i
			svn remove $i
		else
			echo Found $i
		fi
    fi
done
svn status
