#!/bin/bash

alias o="ls -lh"
alias l="ls -lh"
alias e="ls"
alias mk="mkdir -p"
alias u="j" # http://wiki.github.com/joelthelion/autojump/
alias c="cd"

alias a="arun"

# git
alias ga="git add"
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias gds='git diff --staged'
alias gc='git commit'
alias gca='git commit -a'
alias gcm='git commit -m'
alias gcam='git commit -a -m'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status'
alias grm='git rm'
alias gdel="git status | grep 'deleted:' | awk '{print \$3}' | xargs git rm"
alias qg='arun qgit --all'
alias gru='git remote update -p'
