#!/bin/bash

# truncate path if longer than 50 chars
function trunc_path() {
	wd=`pwd`
	wdc=`echo -n "$wd" | wc -c`
	if [ $wdc -lt 40 ]; then
		echo -n "${wd}"
		exit 0
	fi
	rcnt=$((wdc - 19))
	left=`echo "$wd" | cut -c 1-18`
	right=`echo "$wd" | cut -c ${rcnt}-`
	echo -n "${left}...${right}"
}

function parse_svn_dirty {
	local lines=$(svn status 2>/dev/null | grep "^\([ACDIMR?\!\~]\)\|\( [CM]\)" | wc -l)
	[[ $lines -gt 0 ]] && echo "*"
}

function parse_svn_revision {
	local svn_rev=$(svn info 2>/dev/null | grep ^Revision | awk '{ print $2 }')
	[[ -n $svn_rev ]] && echo "(r$svn_rev$(parse_svn_dirty))"
}

function parse_scm {
	[[ $(__git_ps1) ]] && echo $(__git_ps1)
	#parse_svn_revision
}

export GIT_PS1_SHOWDIRTYSTATE=1

reset_style='\[\033[00m\]'
status_style=$reset_style'\[\033[0;90m\]' # gray color; use 0;37m for lighter color
prompt_style=$reset_style
command_style=$reset_style'\[\033[1;29m\]' # bold black

# Reset color for command output
# (this one is invoked every time before a command is executed):
trap 'echo -ne "\e[0m"' DEBUG

function prompt_command {

    # create a $fill of all screen width minus the time string and a space:
    let fillsize=${COLUMNS}-9
    fill=""
    while [ "$fillsize" -gt "0" ]
    do
        fill="-${fill}" # fill with underscores to work on
        let fillsize=${fillsize}-1
    done

    # If this is an xterm set the title to user@host:dir
    case "$TERM" in
    xterm*|rxvt*)
        bname=`basename "${PWD/$HOME/~}"`
        echo -ne "\033]0;${bname}: ${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"
        ;;
    *)
        ;;
    esac

}
PROMPT_COMMAND=prompt_command

PS1="$status_style"'$fill \t\n'"$prompt_style"'\u@\h:\w$(parse_scm)\$'"$command_style "
