#!/bin/bash

# truncate path if longer than 50 chars
function trunc_path() {
	wd=`pwd`
	wdc=`echo -n "$wd" | wc -c`
	if [ $wdc -lt 40 ]; then
		echo -n "${wd}"
		exit 0
	fi
	rcnt=$((wdc - 19))
	left=`echo "$wd" | cut -c 1-18`
	right=`echo "$wd" | cut -c ${rcnt}-`
	echo -n "${left}...${right}"
}

function parse_git_dirty {
	#git diff --quiet HEAD &>/dev/null
	#[[ $? == 1 ]] && echo "*"
	local lines=$(git status | grep -c "(working directory clean)")
	[[ $lines -ne 1 ]] && echo "*"
}

function parse_git_branch {
	 local branch=$(__git_ps1 "%s")
	 [[ $branch ]] && echo "[$branch$(parse_git_dirty)]"
}

function parse_svn_dirty {
	local lines=$(svn status 2>/dev/null | wc -l)
	[[ $lines -gt 0 ]] && echo "*"
}

function parse_svn_revision {
	local svn_rev=$(svn info 2>/dev/null | grep ^Revision | awk '{ print $2 }')
	[[ -n $svn_rev ]] && echo "[r$svn_rev$(parse_svn_dirty)]"
}

function parse_scm {
	parse_git_branch
	parse_svn_revision
}

export PS1='\u@\h:$(trunc_path)$(parse_scm)\$ '

