#!/bin/bash

# truncate path if longer than 50 chars
function trunc_path() {
	wd=`pwd`
	wdc=`echo -n "$wd" | wc -c`
	if [ $wdc -lt 40 ]; then
		echo -n "${wd}"
		exit 0
	fi
	rcnt=$((wdc - 19))
	left=`echo "$wd" | cut -c 1-18`
	right=`echo "$wd" | cut -c ${rcnt}-`
	echo -n "${left}...${right}"
}

function parse_svn_dirty {
	local lines=$(svn status 2>/dev/null | wc -l)
	[[ $lines -gt 0 ]] && echo "*"
}

function parse_svn_revision {
	local svn_rev=$(svn info 2>/dev/null | grep ^Revision | awk '{ print $2 }')
	[[ -n $svn_rev ]] && echo "(r$svn_rev$(parse_svn_dirty))"
}

function parse_scm {
	[[ $(__git_ps1) ]] && echo $(__git_ps1)
	parse_svn_revision
}

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[\033[0;32m\]\u@\h\[\033[0;34m\] \w\[\033[0;33m\]$(parse_scm)\[\033[0;34m\]\$\[\033[00m\] '

